INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (1, '11','11','11','11@test.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (2, '22','22','22','22@test.com');

INSERT INTO QUESTION(ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE) VALUES(1,1,'test','test', CURRENT_TIMESTAMP());
INSERT INTO QUESTION(ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE) VALUES(2,2,'test2','test2', CURRENT_TIMESTAMP());